
 
# Project ideas 

Soumya Banerjee 

Senior Research Fellow and Affiliated Lecturer

University of Cambridge, Cambridge, United Kingdom 

∗ E-mail: sb2333@cam.ac.uk neel.soumya@gmail.com

Office: FC01 (first floor) in the computer science department


I work in explainable AI (xAI) and unconventional approaches to AI. I work at the intersection of complex systems and xAI: I take inspiration from complex systems to suggest new approaches to AI, and use AI to analyze complex systems.


## Projects 

### Foundation models for artificial life


Foundation models for artificial life.

Automating the Search for Artificial Life with Foundation Models

https://arxiv.org/abs/2412.17799

### Multi-agent systems for automated science

Building multi-agent systems and generative AI systems for automated science. 

We will also look at applying these frameworks to other sectors (such as finance, economics, defence, environment, policy, etc.)

Look at:

https://github.com/CMBAgents/cmbagent

https://github.com/CMBAgents/cmbagent/blob/main/docs/notebooks/cmbagent_beta2_demo.ipynb

https://www.aisi.gov.uk/work/long-form-tasks

### Large-language models for designing better jet engines

Use an LLM to perform multi-objective optimization for adaptive flow jet engines

https://www.mdpi.com/2226-4310/10/10/858

### AI safety

Evaluate LLMs for AI safety looking at applications in healthcare, space and nuclear domains

Automated early warning indicators for unsafe usage of LLMs.

https://www.earthdata.nasa.gov/news/blog/ethics-large-language-models-who-controls-future-open-science

NASA - National Aeronautics and Space Administration report about why you can't use LLMs to generate safety/assurance cases

https://www.linkedin.com/feed/update/urn:li:activity:7309730788286124032/

### Reasoning and large language models project 1

Build LLMs to work on SimpleBench

https://simple-bench.com/



### Project idea (Reasoning and large language models)
 
 Build a large language model to solve the Abstraction and Reasoning Corpus Challenge
 
   https://github.com/fchollet/ARC

 Abstraction and Reasoning Corpus Challenge

   https://blog.jovian.ai/finishing-2nd-in-kaggles-abstraction-and-reasoning-challenge-24e59c07b50a

   https://github.com/alejandrodemiquel/ARC_Kaggle

It has been suggested that large language models cannot reason. This project will infuse some reasoning/priors into large language models and apply them to a large reasoning corpus (Abstraction and Reasoning Corpus). 

We can also apply large language models to reasoning in math problems.

This will be a collaboration with Mikel Bober-Irizar.


### Project idea (Explainable AI)

* Contemporary approaches towards explainable AI are model-centric. We will use data-centric approaches to explain the complex interplay between data and models. This will build on and extend published work [1]. This project will be ideal for a student with interest in machine learning and who has coding experience. 
 
 There are many ways in which the work presented in [1] can be extended (either new methods or new application areas). Please get in touch to discuss. 
 


### Project idea: Personalized explainable AI

Tailor machine learning model explanations based on audience (e.g. patients, clinicians, farmers, etc.). Generate natural language explanations from machine learning model and tailor these natural language explanations based on the unique background of the listener/audience.


### Project: Tradeoffs between explainabilty and privacy

Develop explainable machine learning models that explain themselves but do so without leaking personal data. For example, class-contrastive reasoning techniques [1] can be used to generate explanations. But they can inadvertently leak personal data. This project will explore the tradeoff between explainability and privacy (and potentially bias). This will lead to models that balance explainability, privacy and bias.

### Project idea: Explainable privacy preserving machine learning

Develop explainable machine learning models that are also privacy preserving. 

Model explanations will be extracted from machine learning models. However this can lead to leakage of private data. Hence one approach is to add noise to model weights (using differential privacy techniques). This will lead to explainable models that are also privacy preserving.

This can also be done in a federated fashion that will help preserve privacy. 




### Project idea: Generative AI applied to complex systems


This project will involve modelling complex systems (like an epidemic spread) with generative agents. For example, generative agents can be coupled to agent based models. This can be used to simulate epidemics.

https://arxiv.org/abs/2307.04986

https://github.com/bear96/GABM-Epidemic

We will further develop this this framework and apply it to other complex systems (like supply chains, modelling of disinformation, people who are against taking vaccines, conflicts in societies, ecosystem modelling [see below] etc.) 

https://research.csiro.au/atlantis/home/model-components/

We can also apply this to models like the World3 model

https://en.wikipedia.org/wiki/World3

https://github.com/cvanwynsberghe/pyworld3

and models of ecosystems

https://gitlab.com/ecotwin/


### Project idea (Explainable neural cellular automata applied to biology [computational biology project])

Extending the neural cellular automata

https://distill.pub/2020/growing-ca/#experiment-2

and make it more interpretable and explainable.

For example, you can apply it to data from the Game of Life and infer the rules.

https://github.com/lantunes/netomaton/blob/master/demos/game_of_life/README.md

https://github.com/tomgrek/gameoflife

We can also apply it to biological data from cell biology (this can be a computational biology project). We have real world data from cell biology. 

https://greydanus.github.io/2022/05/24/studying-growth/

No experience in biology is required.


### Project idea
 
 * Build a computational model of analogy making and apply it to biomedical and genomic data.
 
 For other project ideas related to explainable AI see the following page:
 
 https://github.com/neelsoumya/special_topics_unconventional_AI/
 
 Broadly this will use concepts like analogies and stories to create new explainable AI methods.
 
 See for example 
 
 https://github.com/Tijl/ANASIME
 
 https://github.com/crazydonkey200/SMEPy

 https://github.com/fargonauts/copycat
 

 
 

### Project idea (Automated Scientific Discovery)
  
This is a project on automatically discovering scientific laws (like Kepler's Law) and invariants (like Boyle's Law) from data.  

This may involve building a model or Bayesian model and/or probabilistic programming model of infection dynamics (like a SIR model) or an intra-cellular regulatory network [5]. This would apply a probabilistic programming model to infection data from different sources.  

Other models include phsyics simulators like pymunk:

http://www.pymunk.org/en/latest/examples.html#planet-py

You would simulate physics based simulations (like pymunk) or other models (like the SIR model above) and develop a machine learning approach to automatically generate insights from this model.

This would be an explainable AI model for a complex model of a physical system.

The project would involve building a model that would generate insights from these complex systems (an artificial model of human creativity).



### Project idea (Automated Scientific Discovery)
  
This is a project on automatically discovering scientific laws (like Kepler's Law) and invariants (like Boyle's Law) from data.  This will enable us to automatically discover conservation laws from data.

One can build a model or Bayesian model and/or probabilistic programming model of a complex systems model like infection dynamics (SIR model) or an intra-cellular regulatory network [5]. 

This would involve building a qualitative process model for a physical system.   

This would be an explainable AI model for a complex model of a physical system.

The project would involve building a model that would generate insights from these complex systems (an artificial model of human creativity).


### Project idea (Automated Scientific Discovery applied to different problems [e.g. healthcare])

This is a project on automatically discovering scientific laws or mathematical equations from data.    

This would involve extending the Ramanujan machine by applying it to other data or other dynamical systems or using another machine learning approach.

https://github.com/RamanujanMachine/RamanujanMachine

Other ideas including extending AI Feynman 2.0 

https://github.com/SJ001/AI-Feynman

or BACON.3

https://github.com/jantzen/BACON

One can also apply symbolic regression approaches like PySR (python) or gramEvol (R).

This can be applied to discover, for example, trigonometric identities.

<!-- one can also apply Bayesian symbolic regression. This can be applied to discover trigonometric identities. This would be a joint project with Challenger Mishra -->

<!-- data can be used from the AI feynman database on Max tegmark's website -->

Other approaches include Bayesian symbolic regression 

https://arxiv.org/abs/1910.08892

https://github.com/ying531/MCMC-SymReg


or seq2seq approaches to symbolic regression

https://openreview.net/pdf?id=W7jCKuyPn1

https://github.com/SymposiumOrganization/NeuralSymbolicRegressionThatScales

This would be an artificial model of human creativity.

Other ideas include discovering ordinary differential equations from data

https://arxiv.org/abs/2211.02830#



### Project idea (Collective intelligence in AI)

Dynamics of collective learning in artificial neural networks, Hopfield networks, self organizing maps and neural gas.


### Project idea (Collective intelligence in AI)
 
This project will investigate collective artifical intelligence in building behaviour (altruism, co-operation, competition) and structures (structures to capture prey). This will use the multi-agent platform MAgent

https://github.com/geek-ai/MAgent

We can also use the EvoJax framework

https://github.com/google/evojax/blob/main/examples/notebooks/EncirclingAgents.ipynb

We can also extend MAgent using dream mechanisms in World Models

https://worldmodels.github.io/

https://smartlabai.medium.com/world-models-a-reinforcement-learning-story-cdcc86093c5


### Project idea (Modelling complex systems with generative agents)

This project will involve modelling complex systems (like an epidemic spread) with generative agents. For example, generative agents can be coupled to agent based models. This can be used to simulate epidemics.

https://arxiv.org/abs/2307.04986

https://github.com/bear96/GABM-Epidemic

We will further develop this this framework and apply it to other complex systems (like supply chains, modelling of disinformation, people who are against taking vaccines, conflicts in societies, ecosystem modelling [see below] etc.) 

https://research.csiro.au/atlantis/home/model-components/

This can also be combined with neural automata (see projects below)



### Project idea (Explainable neural cellular automata applied to biology [computational biology project])

Extending the neural cellular automata

https://distill.pub/2020/growing-ca/#experiment-2

and make it more interpretable and explainable.

For example, you can apply it to data from the Game of Life and infer the rules.

https://github.com/lantunes/netomaton/blob/master/demos/game_of_life/README.md

https://github.com/tomgrek/gameoflife

We can also apply it to biological data from cell biology (this can be a computational biology project). We have real world data from cell biology. 

https://greydanus.github.io/2022/05/24/studying-growth/

<!-- morphology or wave propagation in the Rho GTPase system -->
<!--This would be similar to wave propagation in B-Z systems. We can also apply it to data from the B-Z system. -->

<!-- we can also apply it to data from computational fluid dynamics -->

Another idea is to apply this to simulations from computational fluid dynamics using the software below:

https://github.com/md861/HypFEM

This would be jointly with Mayank Drolia.

This can also be applied to genomic data.




### Simulation of complex systems and societies with large-language models

War and Peace (WarAgent): Large Language Model-based Multi-Agent Simulation of World Wars

https://arxiv.org/pdf/2311.17227.pdf

https://github.com/agiresearch/WarAgent




### Multi-agent collaboration with LLMs

Creating multi-agent systems with LLMs. 

``In many companies, managers routinely decide what roles to hire, and then how to split complex projects — like writing a large piece of software or preparing a research report — into smaller tasks to assign to employees with different specialties. Using multiple agents is analogous. Each agent implements its own workflow, has its own memory (itself a rapidly evolving area in agentic technology: how can an agent remember enough of its past interactions to perform better on upcoming ones?), and may ask other agents for help. Agents can also engage in Planning and Tool Use. This results in a cacophony of LLM calls and message passing between agents that can result in very complex workflows.``

https://github.com/OpenBMB/ChatDev


<!--
### Project idea 11: Biologically inspired machine learning applied to cyber security

This project will involve developing biologically inspired machine learning techniques, like negative selection algorithms [7]. Negative selection algorithms are inspired by how the immune system is trained to detect pathogens. This project will involve developing a biologically inspired machine learning algorithm and applying it to cyber security. An example application would be detecting outliers in network traffic.
-->


<!--
### Project idea 12: AI applied to cyber security

This project will develop AI tools applied to cyber security. 

Ideas include developing and improving on AI based methods for password guessing. See PassGAN: A Deep Learning Approach for Password Guessing

https://arxiv.org/pdf/1709.00440.pdf


<!-- talk on AI applied to cyber security

https://www.youtube.com/watch?v=oBdB61A8Yt8

-->

<!--
Other ideas include extending AI based approaches to generate better phishing URLs. For example, DeepPhish: Simulating Malicious AI

https://albahnsen.files.wordpress.com/2018/05/deepphish-simulating-malicious-ai_submitted.pdf

Other ideas include designing better outlier detection algorithms in network traffic data. For example, one can use ideas from rough sets to design better outlier detection strategies:

Outlier Detection Using Rough Sets

https://link.springer.com/chapter/10.1007/978-3-030-05127-3_7

We can also use autoencoders for detecting outliers in network traffic data.

Other ideas include using deep autoencoders for detecting malicious source code

https://doi.org/10.1016/j.patter.2023.100773
-->


<!--
### Project idea 13

* Other project ideas are generating synthetic data from private datasets like data from electronic healthcare records data [3], other explanatory artificial intelligence (xAI) techniques, privacy preserving machine learning [4], documenting data and models, detecting concept drift [6], etc. 
-->

<!--
### Other ideas

 Project ideas can be developed according to student interests. If you have other project ideas you would like to discuss, please come speak with me.
 -->

<!--
### Computational virology and computational immunology

Some specific projects can involve:

* Inferring biologically relevant parameters for viral infection from time series data

Estimating biologically relevant parameters under uncertainty for experimental within-host murine West Nile virus infection, Soumya Banerjee, Jeremie Guedj, Ruy Ribeiro, Melanie Moses & Alan Perelson Journal of the Royal Society Interface, 13(117), 20160130, 2016

https://royalsocietypublishing.org/doi/full/10.1098/rsif.2016.0130

* Understanding the nature of central tolerance using publicly available genomic data

Influence of correlated antigen presentation on T cell negative selection in the thymus, Soumya Banerjee, SJ Chapman, Journal of the Royal Society Interface, 15(148), 20180311, 2018

https://royalsocietypublishing.org/doi/full/10.1098/rsif.2018.0311

-->
 
## Supervision 
 
 Students will be jointly supervised with Prof. Neil Lawrence or Prof. Pietro Lio.

## Contact

Project ideas can be developed according to student interests. 

Please contact Soumya Banerjee at sb2333@cam.ac.uk or neel.soumya@gmail.com to have an informal chat. Please also send a copy of your CV.

Office: FC01 (first floor) in the computer science department

You can learn more about my work here: 

https://sites.google.com/site/neelsoumya 

## Bigger Picture

The main objective is to develop a suite of techniques inspired by classical AI to inform explainable AI.
This project is part of a wider effort of unconventional approaches to AI. 

## References 

1. Banerjee S, Lio P, Jones PB, Cardinal RN (2021) A class-contrastive human-interpretable machine learning approach to predict mortality in severe mental illness. npj Schizophr 7: 1–13. 

2. Rudin C (2019) Stop explaining black box machine learning models for high stakes decisions and use interpretable models instead. Nat Mach Intell 1: 206–215. 

3. Banerjee S, tom rp Bishop (2022) dsSynthetic: Synthetic data generation for the DataSHIELD federated analysis system. BMC Res Notes 15: 230. 

4. Banerjee S, Sofack GN, Papakonstantinou T, Avraam D, Burton P, et al. (2022) dsSurvival: Privacy preserving survival models for federated individual patient meta-analysis in DataSHIELD. BMC Res Notes 15: 197.

5. Modelling the effects of phylogeny and body size on within-host pathogen replication and immune response, Soumya Banerjee, Alan Perelson, Melanie Moses, Journal of the Royal Society Interface 14(136), 20170479, 2017

6. https://web.archive.org/web/20230606205118/https://www.nannyml.com/blog/when-data-drift-does-not-affect-performance-machine-learning-models, URL accessed June 2023

7. Influence of correlated antigen presentation on T cell negative selection in the thymus, Soumya Banerjee, SJ Chapman, Journal of the Royal Society Interface, 15(148), 20180311, 2018


